add_requires('openssl3')
target("kcflib")
	set_kind("static")
	add_packages("openssl3")
	add_files("src/kcflib/*.c")
	add_headerfiles("include/(kcflib/*.h)")
	add_includedirs("include/kcflib", {public = true})
	add_rules("utils.install.cmake_importfiles")
	add_rules("utils.install.pkgconfig_importfiles")

